DECLARE
    Ln_FLUJOOLD     NUMBER := 67;------FLUJO A DUPLICAR
    Lv_CODCIA       VARCHAR2(3) := '001';---- COMPANIA A DUPLICAR
    Ln_FLUJONEW     NUMBER := 71;------FLUJO NUEVO SI EXISTE// NULL
    Lv_NOM          VARCHAR2(50);------NOMBRE FLUJO NUEVO// NULL
    ----------------------------------------------------
    Ln_MAXEST       NUMBER;
    Ln_DIFEST       NUMBER;
    Ln_MAXSTA       NUMBER;
    Ln_DIFSTA       NUMBER;
BEGIN
-------------DUPLICACION DE FLUJO---------------------
    IF Ln_FLUJONEW IS NULL THEN
        SELECT NVL(MAX(FLUJO_ID),0) +1 INTO Ln_FLUJONEW
        FROM WF_FLUJOS;
        
        INSERT INTO WF_FLUJOS(FLUJO_ID, FL_NOMBRE, FL_DESCRIPCION, FL_ACTIVO, FL_ORDEN)
            SELECT Ln_FLUJONEW, Lv_NOM,Lv_NOM,FL_ACTIVO, Ln_FLUJONEW
            FROM WF_FLUJOS
            WHERE FLUJO_ID = Ln_FLUJOOLD ;
    END IF;
-----------------GENERANDO SECUENCIAS--------------------------
    SELECT NVL(MAX(ESTADO_ID),0)+1 INTO Ln_MAXEST
    FROM WF_ESTADOS;
    
    SELECT Ln_MAXEST - NVL(MIN(ESTADO_ID),0) INTO Ln_DIFEST
    FROM WF_ESTADOS
    WHERE EST_FLUJO_ID = Ln_FLUJOOLD
    AND EST_CODCIA = Lv_CODCIA;
    
    
    SELECT NVL(MAX(FLUJO_ESTATUS_ID),0)+1 INTO Ln_MAXSTA
    FROM WF_FLUJO_ESTATUS;

    SELECT Ln_MAXSTA - NVL(MIN(FLUJO_ESTATUS_ID),0) INTO Ln_DIFSTA
    FROM WF_FLUJO_ESTATUS
    WHERE FLS_FLUJO_ID = Ln_FLUJOOLD;
-------------------DUPLICACION DE ESTADOS-------------------   
    INSERT INTO WF_ESTADOS(ESTADO_ID, EST_FLUJO_ID, EST_NOMBRE, EST_APEXPAGE, EST_DESCRIPCION, EST_ACTIVO, 
                            EST_ORDEN, EST_INI, EST_ESTATUS_INI, EST_TIEMPOMAXIMO, EST_FONTAWESOME, EST_APP_ALIAS, EST_CODCIA, EST_TITULO)
    SELECT Ln_DIFEST + ESTADO_ID, Ln_FLUJONEW, EST_NOMBRE, EST_APEXPAGE, EST_DESCRIPCION, EST_ACTIVO, 
                            EST_ORDEN, EST_INI, Ln_DIFSTA + EST_ESTATUS_INI, EST_TIEMPOMAXIMO, EST_FONTAWESOME, EST_APP_ALIAS, EST_CODCIA, EST_TITULO
    FROM WF_ESTADOS
    WHERE EST_FLUJO_ID = Ln_FLUJOOLD
    AND EST_CODCIA = Lv_CODCIA;
    
-------------------DUPLICACION DE ESTATUS-------------------
    
    INSERT INTO WF_FLUJO_ESTATUS(FLUJO_ESTATUS_ID, FLS_NOMBRE, FLS_DESCRIPCION, FLS_FLUJO_ID, FLS_ORDEN, FLS_MSG_RECEPTOR, FLS_DESCARTAR)
    SELECT Ln_DIFSTA + FLUJO_ESTATUS_ID, FLS_NOMBRE, FLS_DESCRIPCION, Ln_FLUJONEW, FLS_ORDEN, FLS_MSG_RECEPTOR, FLS_DESCARTAR
    FROM WF_FLUJO_ESTATUS
    WHERE FLS_FLUJO_ID = Ln_FLUJOOLD;
-------------------------------------DUPLICACION DE PASOS FLUJO---------------
    INSERT INTO WF_PASOS_FLUJO(PFL_DESCRIPCION, PFL_ESTADO_ACTUAL_ID, PFL_ESTADO_SIGUIENTE_ID, PFL_ESTATUS_ID, PFL_FLUJO_ID, 
                                PFL_ESTATUS_SIGU_ID, PFL_PASO_FINAL, PFL_DESCARTADO, PFL_CODCIA)
    SELECT PFL_DESCRIPCION, Ln_DIFEST + PFL_ESTADO_ACTUAL_ID, Ln_DIFEST + PFL_ESTADO_SIGUIENTE_ID, Ln_DIFSTA + PFL_ESTATUS_ID, Ln_FLUJONEW, 
                                Ln_DIFSTA + PFL_ESTATUS_SIGU_ID, PFL_PASO_FINAL, PFL_DESCARTADO, PFL_CODCIA
    FROM WF_PASOS_FLUJO
    WHERE PFL_FLUJO_ID = Ln_FLUJOOLD
    AND PFL_CODCIA = Lv_CODCIA;
    
-------------------------------------DUPLICACION DE PROCESOS---------------    
    INSERT INTO WF_PROCESOS(NOMBRE_PROCESO, ESTADO_ID, ESTATUS_ID, WFP_ORDEN, WFP_ACTIVO, WFP_CODCIA, WFP_FLUJO_ID)
    SELECT NOMBRE_PROCESO, Ln_DIFEST+ESTADO_ID, Ln_DIFSTA+ESTATUS_ID, WFP_ORDEN, WFP_ACTIVO, WFP_CODCIA, Ln_FLUJONEW
    FROM WF_PROCESOS
    WHERE WFP_FLUJO_ID = Ln_FLUJOOLD
    AND WFP_CODCIA = Lv_CODCIA;
END;