--ORACLE APPLICATION EXPRESS
--APEX
--HOW TO UPDATE A ATRTIBUTE OF AN ITEM IN ALL APPLICATIONS THAT THIS ITEM IS USED. 

--EXAMPLE
--WE ARE LOOKING FOR THIS ITEM "PLUGIN_COM_SKILLBUILDERS_SUPER_LOV"

--WE ARE GOING TO REPLACE THIS ATTRIBUTE "NOT_ENTERABLE"
--WITH THIS NEW ATTRIBUTE "ENTERABLE_RESTRICTED"

update wwv_flow_step_items
set  attribute_08 = 'ENTERABLE_RESTRICTED'
where upper(display_as) = 'PLUGIN_COM_SKILLBUILDERS_SUPER_LOV'
and attribute_08 = 'NOT_ENTERABLE';
