DECLARE
V_SCHEMA_OLD    VARCHAR2(100);
V_SCHEMA_NEW    VARCHAR2(100);
BEGIN
UPDATE APEX_220100.WWV_FLOW_STEP_PROCESSING
SET ATTRIBUTE_01 =V_SCHEMA_NEW
WHERE ATTRIBUTE_01 = V_SCHEMA_OLD;

UPDATE APEX_220100.WWV_FLOW_PAGE_PLUGS
SET QUERY_OWNER = V_SCHEMA_NEW
WHERE QUERY_OWNER = V_SCHEMA_OLD;
end;