DECLARE
    V_SCHEMA_OLD    VARCHAR2(100) := 'ECOOPDESA';--ECOOPDESA, ECOOPHISTORICO, ECOOPMULTIMEDIA
    V_SCHEMA_NEW    VARCHAR2(100) := 'BMSCORE';--BMSCORE, BMSHISTO, BMSMEDIA
    V_ACT       NUMBER;
    
    cursor c_app is select * from APEX_220100.WWV_FLOWS
    inner join BMSCORE.SEG_APLICACIONES_MAP on map_app_alias = alias;
BEGIN
for i in c_app loop
    DBMS_OUTPUT.PUT_LINE('APLICACION - '||i.ID ||' - '||i.NAME);
    DBMS_OUTPUT.PUT_LINE('ESQUEMAS A CAMBIAR DE  - '||V_SCHEMA_OLD ||' AL '||V_SCHEMA_NEW);
    ------------------------------------------------------------------------REGIONS
    ----UPDATE REGIONS REPORT
    SELECT COUNT(*) INTO V_ACT FROM  APEX_220100.WWV_FLOW_PAGE_PLUGS
    WHERE FLOW_ID = i.ID --APP_ID --AND PAGE_ID = 10 --APP_PAGE_ID
    AND QUERY_TYPE = 'SQL'
    AND UPPER(PLUG_SOURCE) LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN
        UPDATE APEX_220100.WWV_FLOW_PAGE_PLUGS
        SET PLUG_SOURCE = REPLACE(UPPER(PLUG_SOURCE),V_SCHEMA_OLD,V_SCHEMA_NEW)
        WHERE FLOW_ID = i.ID --APP_ID --AND PAGE_ID = 10 --APP_PAGE_ID
        AND QUERY_TYPE = 'SQL'
        AND UPPER(PLUG_SOURCE) LIKE '%'||V_SCHEMA_OLD||'%';

        DBMS_OUTPUT.PUT_LINE('REPORTES ACTUALIZADOS - '||V_ACT);
    END IF;

    ---UPDATE DISPLAY ONLY CONDITION
   
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_PAGE_PLUGS
    WHERE FLOW_ID = i.ID --APP_ID AND PAGE_ID = 95 --APP_PAGE_ID
    AND (PLUG_DISPLAY_WHEN_COND2 in ('PLSQL','SQL') OR PLUG_DISPLAY_CONDITION_TYPE IN ('EXISTS','NOT_EXISTS'))
    AND UPPER(PLUG_DISPLAY_WHEN_CONDITION) LIKE '%'||V_SCHEMA_OLD||'%';
    
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_PAGE_PLUGS
    SET PLUG_DISPLAY_WHEN_CONDITION = REPLACE(UPPER(PLUG_DISPLAY_WHEN_CONDITION),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID --APP_ID AND PAGE_ID = 95 --APP_PAGE_ID
    AND (PLUG_DISPLAY_WHEN_COND2 in ('PLSQL','SQL') OR PLUG_DISPLAY_CONDITION_TYPE IN ('EXISTS','NOT_EXISTS'))
    AND UPPER(PLUG_DISPLAY_WHEN_CONDITION) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('REGIONES DISPLAY ONLY WHEN ACTUALIZADOS - '||V_ACT);
    END IF;

    --UPDATE READ ONLY CONDITIION 
    SELECT COUNT(*) INTO V_ACT FROM  APEX_220100.WWV_FLOW_PAGE_PLUGS
    WHERE FLOW_ID = i.ID --APP_ID  -- AND PAGE_ID = 95 --APP_PAGE_ID
    AND (PLUG_READ_ONLY_WHEN2 in ('PLSQL','SQL') OR PLUG_READ_ONLY_WHEN_TYPE IN ('EXISTS','NOT_EXISTS'))
    AND UPPER(PLUG_READ_ONLY_WHEN) LIKE '%'||V_SCHEMA_OLD||'%';
    
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_PAGE_PLUGS
    SET PLUG_READ_ONLY_WHEN = REPLACE(UPPER(PLUG_READ_ONLY_WHEN),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID --APP_ID  -- AND PAGE_ID = 95 --APP_PAGE_ID
    AND (PLUG_READ_ONLY_WHEN2 in ('PLSQL','SQL') OR PLUG_READ_ONLY_WHEN_TYPE IN ('EXISTS','NOT_EXISTS'))
    AND UPPER(PLUG_READ_ONLY_WHEN) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('REGIONES READ ONLY WHEN ACTUALIZADOS - '||V_ACT);
    END IF;

    -----------------------------------------------------------------------------ITEMS
    --UPDATE DEFAULT
    SELECT COUNT(*) INTO V_ACT FROM  APEX_220100.WWV_FLOW_STEP_ITEMS
    WHERE FLOW_ID = i.ID --AND FLOW_STEP_ID = 95
    AND (ITEM_DEFAULT_LANGUAGE  = 'PLSQL' or ITEM_DEFAULT_TYPE = 'SQL_QUERY')
    AND UPPER(ITEM_DEFAULT) LIKE '%'||V_SCHEMA_OLD||'%';
    
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_STEP_ITEMS
    SET ITEM_DEFAULT =  REPLACE(UPPER(ITEM_DEFAULT),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID --AND FLOW_STEP_ID = 95
    AND (ITEM_DEFAULT_LANGUAGE  = 'PLSQL' or ITEM_DEFAULT_TYPE = 'SQL_QUERY')
    AND UPPER(ITEM_DEFAULT) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('ITEM DEFAULT ACTUALIZADOS - '||V_ACT);
    END IF;

    --UPDATE SOURCE
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_STEP_ITEMS
    WHERE FLOW_ID = i.ID --AND FLOW_STEP_ID = 95
    AND (SOURCE_LANGUAGE  = 'PLSQL' or SOURCE_TYPE = 'QUERY')
    AND UPPER(SOURCE) LIKE '%'||V_SCHEMA_OLD||'%';
    
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_STEP_ITEMS
    SET SOURCE  =  REPLACE(UPPER(SOURCE),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID --AND FLOW_STEP_ID = 95
    AND (SOURCE_LANGUAGE  = 'PLSQL' or SOURCE_TYPE = 'QUERY')
    AND UPPER(SOURCE) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('ITEM SOURCE ACTUALIZADOS - '||V_ACT);
    END IF;

    ----READ ONLY ITEM
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_STEP_ITEMS
    WHERE FLOW_ID = i.ID
    AND (READ_ONLY_WHEN2 IN ('SQL','PLSQL') OR READ_ONLY_WHEN_TYPE IN ('EXISTS', 'NOT_EXISTS'))
    AND UPPER(READ_ONLY_WHEN) LIKE '%'||V_SCHEMA_OLD||'%';
    
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_STEP_ITEMS
    SET READ_ONLY_WHEN  =  REPLACE(UPPER(READ_ONLY_WHEN),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID
    AND (READ_ONLY_WHEN2 IN ('SQL','PLSQL') OR READ_ONLY_WHEN_TYPE IN ('EXISTS', 'NOT_EXISTS'))
    AND UPPER(READ_ONLY_WHEN) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('ITEM READ ONLY ACTUALIZADOS - '||V_ACT);
    END IF;

    ---DISPLAY ONLY
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_STEP_ITEMS
    WHERE FLOW_ID = i.ID
    AND (DISPLAY_WHEN2 IN ('SQL','PLSQL') OR DISPLAY_WHEN_TYPE IN ('EXISTS', 'NOT_EXISTS'))
    AND UPPER(DISPLAY_WHEN) LIKE '%'||V_SCHEMA_OLD||'%';
    
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_STEP_ITEMS
    SET DISPLAY_WHEN = REPLACE(UPPER(DISPLAY_WHEN),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID
    AND (DISPLAY_WHEN2 IN ('SQL','PLSQL') OR DISPLAY_WHEN_TYPE IN ('EXISTS', 'NOT_EXISTS'))
    AND UPPER(DISPLAY_WHEN) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('ITEM DISPLAY ONLY ACTUALIZADOS - '||V_ACT);
    END IF;

    ----UPDATE LOV NOT NAMED 
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_STEP_ITEMS
    WHERE FLOW_ID = i.ID --AND FLOW_STEP_ID = 55
    AND NAMED_LOV IS NULL
    AND LOV IS NOT NULL
    AND UPPER(LOV) LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_STEP_ITEMS
    SET LOV = REPLACE(UPPER(LOV),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID --AND FLOW_STEP_ID = 55
    AND NAMED_LOV IS NULL
    AND LOV IS NOT NULL
    AND UPPER(LOV) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('LIST OF VALUES NOT NAMED ACTUALIZADOS - '||V_ACT);
    END IF;

    ---- LIST OF VALUES
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_LISTS_OF_VALUES$
    WHERE FLOW_ID = i.ID
    AND UPPER(LOV_QUERY) LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_LISTS_OF_VALUES$
    SET LOV_QUERY = REPLACE(UPPER(LOV_QUERY),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID
    AND UPPER(LOV_QUERY) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('LIST OF VALUES ACTUALIZADOS - '||V_ACT);
    END IF;

    --- ITEMS NAMED
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_STEP_ITEMS
    WHERE FLOW_ID = i.ID --AND FLOW_STEP_ID = 55
    AND NAMED_LOV IS NOT NULL
    AND LOV IS NOT NULL
    AND UPPER(LOV) LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_STEP_ITEMS
    SET LOV = REPLACE(UPPER(LOV),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID --AND FLOW_STEP_ID = 55
    AND NAMED_LOV IS NOT NULL
    AND LOV IS NOT NULL
    AND UPPER(LOV) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('LIST OF VALUES NAMED ACTUALIZADOS - '||V_ACT);
    END IF;

    ---LISTS
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_LISTS
    WHERE FLOW_ID = i.ID
    AND UPPER(LIST_QUERY) LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_LISTS
    SET LIST_QUERY = REPLACE(UPPER(LIST_QUERY),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID
    AND UPPER(LIST_QUERY) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('LISTAS ACTUALIZADOS - '||V_ACT);
    END IF;

    ---DYNAMIC ACTIONS
    ---CONDITIONAL
    SELECT COUNT(*) INTO V_ACT FROM  APEX_220100.WWV_FLOW_PAGE_DA_EVENTS
    WHERE FLOW_ID = i.ID
    AND (DISPLAY_WHEN_TYPE IN ('NOT_EXISTS', 'EXISTS') OR DISPLAY_WHEN_COND2 IN ('SQL','PLSQL'))
    AND UPPER(DISPLAY_WHEN_COND) LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_PAGE_DA_EVENTS
    SET DISPLAY_WHEN_COND = REPLACE(UPPER(DISPLAY_WHEN_COND),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID
    AND (DISPLAY_WHEN_TYPE IN ('NOT_EXISTS', 'EXISTS') OR DISPLAY_WHEN_COND2 IN ('SQL','PLSQL'))
    AND UPPER(DISPLAY_WHEN_COND) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('DYNAMIC ACTIONS CONDITION ACTUALIZADOS - '||V_ACT);
    END IF;

    ---PLSQL
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_PAGE_DA_ACTIONS
    WHERE FLOW_ID = i.ID
    AND ATTRIBUTE_05 = 'PLSQL'
    AND UPPER(ATTRIBUTE_01) LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_PAGE_DA_ACTIONS
    SET ATTRIBUTE_01 = REPLACE(UPPER(ATTRIBUTE_01),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID
    AND ATTRIBUTE_05 = 'PLSQL'
    AND UPPER(ATTRIBUTE_01) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('DYNAMIC ACTION PLSQL ACTUALIZADOS - '||V_ACT);
    END IF;

    ----VALIDACIONES
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_STEP_VALIDATIONS
    WHERE FLOW_ID = i.ID
    AND VALIDATION2 = 'PLSQL'
    AND UPPER(VALIDATION) LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_STEP_VALIDATIONS
    SET VALIDATION = REPLACE(UPPER(VALIDATION),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID
    AND VALIDATION2 = 'PLSQL'
    AND UPPER(VALIDATION) LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('VALIDACIONES ACTUALIZADOS - '||V_ACT);
    END IF;

    ----PROCESOS
    SELECT COUNT(*) INTO V_ACT FROM APEX_220100.WWV_FLOW_STEP_PROCESSING
    WHERE FLOW_ID = i.ID
    AND PROCESS_CLOB_LANGUAGE = 'PLSQL'
    AND PROCESS_SQL_CLOB LIKE '%'||V_SCHEMA_OLD||'%';
    IF V_ACT > 0 THEN 
    UPDATE APEX_220100.WWV_FLOW_STEP_PROCESSING
    SET PROCESS_SQL_CLOB = REPLACE(UPPER(PROCESS_SQL_CLOB),V_SCHEMA_OLD,V_SCHEMA_NEW)
    WHERE FLOW_ID = i.ID
    AND PROCESS_CLOB_LANGUAGE = 'PLSQL'
    AND PROCESS_SQL_CLOB LIKE '%'||V_SCHEMA_OLD||'%';

    DBMS_OUTPUT.PUT_LINE('PROCESOS ACTUALIZADOS - '||V_ACT);
    END IF;
    DBMS_OUTPUT.PUT_LINE('---------------------------------');    
end loop;
END;