-- asignar breadcrumbs en el breadcrumb bar 
update  apex_220100.WWV_FLOW_PAGE_PLUGS
SET PLUG_DISPLAY_POINT = 'REGION_POSITION_01'
where PLUG_SOURCE_TYPE = 'NATIVE_BREADCRUMB'
and flow_id = 144
AND PLUG_DISPLAY_POINT != 'REGION_POSITION_01';


-- asignar body_1, body_2, body_3  a body
update  apex_220100.WWV_FLOW_PAGE_PLUGS
SET PLUG_DISPLAY_POINT = 'BODY'
where flow_id = 144
AND PLUG_SOURCE_TYPE != 'NATIVE_BREADCRUMB'
AND PLUG_DISPLAY_POINT != 'BODY'
and PLUG_DISPLAY_POINT like 'BODY%';

-- actualizar ALWAYS A un DB SOURCE 

UPDATE APEX_220100.WWV_FLOW_STEP_ITEMS
   SET USE_CACHE_BEFORE_DEFAULT = 'NO'
WHERE     FLOW_ID = 119 --APLICACION
       AND SOURCE_TYPE = 'DB_COLUMN' -- CUANDO SEAN DE BASE DE DATOS
       AND SOURCE IS NOT NULL -- VALIDO QUE EL SOURCE NO ESTE NULO POR SIACASO...
       AND item_source_plug_id IS NULL; -- ESTA VALIDACION LA TENIA ORACLE COMO TAL EN LA VISTA...
