--SUPER QUERY 
--QUERY THAT SEARCH IN YOUR DATABASE A PORTION OF CODE
--PARAMETERS:
--SCHEMA_NAME = SCHEMA WHERE YOU WANT TO SEARCH THE PORTION OF CODE
--STRING_TO_SEARCH = PORTION OF CODE YOU ARE LOOKING FOR

--DATABASE
SELECT NAME AS APPLICATION_ID, TYPE as APPLICATION_NAME, LINE AS PAGE_ID, substr(text,1,200) as place
FROM DBA_SOURCE 
where UPPER(DBA_SOURCE.text) like '%'||:STRING_TO_SEARCH||'%' AND OWNER = :SCHEMA_NAME;

--ORACLE APPLICATION EXPRESS (APEX) INTERACTIVE REPORTS
select to_char(APPLICATION_ID), APPLICATION_NAME, PAGE_ID, REGION_NAME as lugar 
from apex_application_page_ir 
where   upper(sql_query) like '%'||:STRING_TO_SEARCH||'%';

--ORACLE APPLICATION EXPRESS (APEX) PROCEDURES
select to_char(APPLICATION_ID), APPLICATION_NAME, PAGE_ID,PROCESS_NAME AS LUGAR 
from apex_application_page_proc 
where  upper(process_source) like '%'||:STRING_TO_SEARCH||'%'; 

--ORACLE APPLICATION EXPRESS (APEX) LIST OF VALUES
select * 
from apex_application_LOVS 
where  upper(LIST_OF_VALUES_QUERY) like '%'||:STRING_TO_SEARCH||'%'; 

--ORACLE APPLICATION EXPRESS (APEX) LISTS
select * 
from apex_application_lists 
where  upper(list_query) like '%'||:STRING_TO_SEARCH||'%'; 
